#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running build process..."
npm run build

# If the build fails, the commit will be aborted
if [ $? -ne 0 ]; then
  echo "Build failed. Commit aborted."
  exit 1
fi
